title: Planning.wiki - The AI Planning & PDDL Wiki
email: adam.green@kcl.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  A Wiki for Artificial Intelligence Planning and the language of it, PDDL. 
  Everything to get started in the world of AI Planning. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://planning.wiki" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thegreenwords
github_username:  nergmada

color_scheme: "dark"

search_enabled: true

aux_links:
  "Report an issue with this page":
    - "//github.com/nergmada/pddl-reference/issues/new/choose"

ga_tracking: UA-78110061-3

# Build settings
markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll-plannertags
  - jekyll-gitauthors
  - jekyll-redirect-from


  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
